import { chromium } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';
import { getAdminConnection, getLoginUrl } from '../utils/auth';
import { installPopupHandler } from '../utils/popup-handler';

/**
 * Tooling API Spy Agent
 * 
 * Analyzes a live Salesforce page (like a Custom LWC or Managed Package UI),
 * correlates the visible DOM structure with Tooling API metadata,
 * and automatically generates a robust Page Object class.
 */

async function runSpy(recordUrl: string, pageObjectName: string) {
  console.log(`🕵️‍♂️ Launching Tooling API Spy Agent for: ${pageObjectName}`);
  
  const conn = await getAdminConnection();
  const loginUrl = await getLoginUrl(conn);

  const browser = await chromium.launch({ headless: false }); // Needs to be visible for layout parsing
  const context = await browser.newContext();
  const page = await context.newPage();

  console.log('🔑 Authenticating...');
  await page.goto(loginUrl);
  await page.waitForLoadState('networkidle');
  
  await installPopupHandler(page);

  console.log(`🌐 Navigating to target: ${recordUrl}`);
  // If recordUrl is just an ID, construct the URL
  const fullUrl = recordUrl.startsWith('http') ? recordUrl : `${conn.instanceUrl}/lightning/r/${recordUrl}/view`;
  await page.goto(fullUrl);
  await page.waitForLoadState('networkidle');
  await page.waitForTimeout(5000); // Wait for LWC to fully render

  console.log('🔍 Scanning Live DOM and Custom Components...');
  
  // Inject script to extract all interactive elements and their metadata
  const elements = await page.evaluate(() => {
    const results: any[] = [];
    
    // Find all inputs, buttons, and custom web components
    const query = 'input, textarea, select, button, a[role="button"], [class*="lightning-"], [nodeName^="C-"]';
    
    // Function to recursively search shadow roots
    const traverse = (root: Document | ShadowRoot | Element) => {
      const nodes = root.querySelectorAll(query);
      nodes.forEach((node) => {
        const el = node as HTMLElement;
        if (el.offsetWidth > 0 && el.offsetHeight > 0) { // Must be visible
          
          let labelText = '';
          let actionName = '';

          // Heuristics for label extraction
          if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
            const id = el.getAttribute('id');
            if (id) {
              // Try to find an associated label
              const labelEl = document.querySelector(`label[for="${id}"]`);
              if (labelEl) labelText = labelEl.textContent || '';
            }
            if (!labelText) {
              const ariaLabel = el.getAttribute('aria-label');
              if (ariaLabel) labelText = ariaLabel;
            }
            if (!labelText) {
              // Look at parent or sibling text
              const parent = el.closest('lightning-input, c-custom-field, .slds-form-element');
              if (parent) {
                const labelTarget = parent.querySelector('label');
                if (labelTarget) labelText = labelTarget.textContent || '';
              }
            }
            actionName = `fill${labelText.replace(/[^a-zA-Z0-9]/g, '')}`;
          } else if (el.tagName === 'BUTTON' || (el.tagName === 'A' && el.getAttribute('role') === 'button')) {
            labelText = el.textContent || el.getAttribute('title') || el.getAttribute('aria-label') || '';
            actionName = `click${labelText.replace(/[^a-zA-Z0-9]/g, '')}`;
          }

          if (labelText && labelText.trim() !== '') {
            results.push({
              tag: el.tagName.toLowerCase(),
              type: el.getAttribute('type') || null,
              label: labelText.trim(),
              actionName,
              classes: el.className,
              isShadow: !!el.getRootNode().host // Is it inside a shadow DOM?
            });
          }
        }
      });

      // Recurse into children's shadow roots
      const allElements = root.querySelectorAll('*');
      allElements.forEach((el) => {
        if (el.shadowRoot) traverse(el.shadowRoot);
      });
    };

    traverse(document);
    
    // Deduplicate
    const unique = new Map();
    results.forEach(r => unique.set(r.actionName, r));
    return Array.from(unique.values());
  });

  console.log(`✨ Discovered ${elements.length} unique interactive elements.`);

  console.log('📝 Generating Page Object Class...');
  
  let classContent = `import type { Page, Locator } from '@playwright/test';\n`;
  classContent += `import { IframeEngine } from '../utils/iframe-engine';\n`;
  classContent += `import { DynamicLocatorEngine } from '../utils/locator-engine';\n\n`;
  
  classContent += `/**\n * Auto-Generated Page Object for ${pageObjectName}\n`;
  classContent += ` * Generated by Tooling API Spy Agent\n */\n`;
  classContent += `export class ${pageObjectName} {\n`;
  classContent += `  private locatorEngine: DynamicLocatorEngine;\n\n`;
  classContent += `  constructor(private page: Page) {\n`;
  classContent += `    this.locatorEngine = new DynamicLocatorEngine(page);\n`;
  classContent += `  }\n\n`;

  for (const el of elements) {
    if (!el.actionName) continue;
    
    if (el.actionName.startsWith('fill')) {
      classContent += `  async ${el.actionName}(value: string): Promise<void> {\n`;
      classContent += `    console.log('[${pageObjectName}] Filling ${el.label} with: ' + value);\n`;
      classContent += `    const input = await this.locatorEngine.locateInputByLabel('${el.label}');\n`;
      classContent += `    if (input) {\n`;
      classContent += `      await input.click();\n`;
      classContent += `      await input.fill(value);\n`;
      classContent += `    } else {\n`;
      classContent += `      throw new Error('Could not dynamically locate input for: ${el.label}');\n`;
      classContent += `    }\n`;
      classContent += `  }\n\n`;
    } else if (el.actionName.startsWith('click')) {
      classContent += `  async ${el.actionName}(): Promise<void> {\n`;
      classContent += `    console.log('[${pageObjectName}] Clicking ${el.label}');\n`;
      classContent += `    const btn = await IframeEngine.findVisibleLocator(this.page, async (root) => {\n`;
      classContent += `      const target = root.getByRole('button', { name: '${el.label}' }).first();\n`;
      classContent += `      return await target.isVisible().catch(() => false) ? target : null;\n`;
      classContent += `    });\n`;
      classContent += `    if (btn) {\n`;
      classContent += `      await btn.click();\n`;
      classContent += `    } else {\n`;
      classContent += `      throw new Error('Could not dynamically locate button for: ${el.label}');\n`;
      classContent += `    }\n`;
      classContent += `  }\n\n`;
    }
  }

  classContent += `}\n`;

  const poPath = path.resolve(__dirname, '..', 'page-objects', `${pageObjectName}.ts`);
  fs.writeFileSync(poPath, classContent, 'utf8');
  
  console.log(`✅ Successfully generated Page Object: ${poPath}`);
  
  console.log('🔌 Registering new Custom Page Object with JSON Runner...');
  
  const runnerPath = path.resolve(__dirname, '..', 'executor', 'json-runner.spec.ts');
  let runnerCode = fs.readFileSync(runnerPath, 'utf8');
  
  // Build the switch cases to inject
  let casesToInject = `    // ── AUTO-GENERATED: ${pageObjectName} ────────────────────\n`;
  for (const el of elements) {
    if (!el.actionName) continue;
    const actionVerb = `${pageObjectName}:${el.actionName}`;
    
    casesToInject += `    case '${actionVerb}': {\n`;
    casesToInject += `      const { ${pageObjectName} } = require('../page-objects/${pageObjectName}');\n`;
    casesToInject += `      const po = new ${pageObjectName}(page);\n`;
    if (el.actionName.startsWith('fill')) {
      casesToInject += `      await po.${el.actionName}(resolved.value);\n`;
    } else {
      casesToInject += `      await po.${el.actionName}();\n`;
    }
    casesToInject += `      break;\n`;
    casesToInject += `    }\n`;
  }
  
  // Inject right before the default framework limitation trap
  const trapMarker = '    // ── FRAMEWORK LIMITATION TRAP ─────────────────────────';
  if (runnerCode.includes(trapMarker)) {
    runnerCode = runnerCode.replace(trapMarker, casesToInject + '\n' + trapMarker);
    fs.writeFileSync(runnerPath, runnerCode, 'utf8');
    console.log(`✅ Dynamically injected ${elements.length} new custom actions into json-runner.spec.ts`);
  } else {
    console.warn(`⚠️ Could not find injection marker in json-runner.spec.ts. You must manually register these actions.`);
  }

  await browser.close();
  console.log('🏁 Spy Agent Complete.');
}

const urlArg = process.argv[2];
const nameArg = process.argv[3] || 'CustomAppPage';

if (!urlArg) {
  console.error('Usage: npx ts-node spy-agent.ts <Salesforce_URL_or_Record_ID> <PageObjectName>');
  process.exit(1);
}

runSpy(urlArg, nameArg).catch(err => {
  console.error('Spy Agent Failed:', err);
  process.exit(1);
});
